clone:
  git:
    image: plugins/git
    depth: 5

pipeline:
  phpunit:
    image: composer
    commands:
      - composer install -q --prefer-dist
  nodejs:
    image: node
    commands:
      - npm install
      - npm run test
