build:
  cache:
    directories:
      - vendor
      - bin
      - node_modules
      - ~/.composer
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override: [ js-scrutinizer-run ]