filter:
  excluded_paths:
    - "tests/"
    - "test/"
    - "assets/"
  dependency_paths:
    - "dist/"
build:
  cache:
    directories:
      - vendor
      - bin
      - node_modules
      - ~/.composer
  nodes:
    analysis:
      resources:
        cpus: 4
      project_setup:
        override: true
      tests:
        override:
          - js-scrutinizer-run
          - eslint-run "libs/**"

