filter:
  excluded_paths:
    - "tests/"
    - "test/"
    - "assets/"
  dependency_paths:
    - "dist/"
build:
  cache:
    directories:
      - vendor
      - bin
      - node_modules
      - ~/.composer
      - tmp
  environment:
    google_chrome:
      use_latest: true
    node: v10.14.2
  nodes:
    analysis:
      resources:
        cpus: 4
      project_setup:
        override: true
      tests:
        override:
          - command: 'npm install npm@latest typescript node-sass sass -g'
          - js-scrutinizer-run
          - eslint-run "libs/js/**"
          - eslint-run "libs/compiler/**"

