os:
  - linux
dist: xenial

language:
  - node_js
  - php

node_js:
  - "10"
php:
  - nightly

cache:
  directories:
    - node_modules
    - vendor
    - tmp

env:
  - TOXENV=py27

before_script:
  - npm install -g gulp typescript grunt eslint tslint

install:
  - npm install
  - tsc -p tsconfig.build.json
  - tsc -p tsconfig.precompiler.json
  - tsc -p tsconfig.compiler.json
  - composer install

script:
  - gulp build

branches:
  only:
    - master

jobs:
  allow_failures:
    - os: linux
  include:
    - os: linux
      python: 2.7
      env: TOXENV=py27
