os:
  - linux
dist: xenial

language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules
    - vendor
    - tmp

env:
  - TOXENV=py27

before_script:
  - npm install -g gulp typescript grunt eslint tslint

install:
  - npm install
  - tsc -p tsconfig.build.json
  - tsc -p tsconfig.precompiler.json
  - tsc -p tsconfig.compiler.json

script:
  - gulp build

branches:
  only:
    - master

jobs:
  allow_failures:
    - os: linux
  include:
    - os: linux
      python: 2.7
      env: TOXENV=py27
