jobs:
  build:
    working_directory: ~/attraction-wars-server
    docker:
      # Specify the version you desire here
      #- image: misterio92/ci-php-node
      - image: circleci/php:latest
      #- image: circleci/node:10.0.0

    steps:
      - run:
          name: Install Requirements
          command: |
            sudo apt-get update
            sudo apt-get install -y libmcrypt-dev libsqlite3-dev libfreetype6-dev libjpeg62-turbo-dev libpng-dev zlib1g-dev nodejs dh-autoreconf
            sudo docker-php-ext-configure gd
            sudo docker-php-ext-install -j$(nproc) iconv gd zip pdo_mysql pdo_sqlite
            #sudo npm install -g npm@latest
            #sudo npm install -g gulp typescript grunt eslint tslint snyk depcheck

      - restore_cache:
          keys:
            - node-v1-{{ checksum "package.json" }}
            - node-v1-
      - run:
          name: Install Node Dependencies
          command: |
            node --version
            npm --version
            npm install

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths:
            - node_modules
