# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
orbs: # declare what orbs we are going to use
  node: circleci/node@2.0.2 # the node orb provides common node-related configuration

workflows:
  version: 2.1 # using 2.1 provides access to orbs and other features
  php_worker:
    jobs:
      build:
        docker:
          - image: circleci/php:latest
        steps:
          - run:
              name: Install Requirements
              command: |
                sudo apt-get update
                sudo apt-get install -y libmcrypt-dev libsqlite3-dev libfreetype6-dev libjpeg62-turbo-dev libpng-dev zlib1g-dev
                sudo docker-php-ext-configure gd
                sudo docker-php-ext-install -j$(nproc) iconv gd zip pdo_mysql pdo_sqlite
          - run:
              name: Update Composer
              command: sudo composer self-update

          - checkout

          - restore_cache:
              keys:
                - composer-v1-{{ checksum "composer.lock" }}
                - composer-v1-
          - run:
              name: Install Composer Dependencies
              command: composer install -n --prefer-dist --ignore-platform-reqs --optimize-autoloader
          - save_cache:
              key: composer-v1-{{ checksum "composer.lock" }}
              paths:
                - vendor
